
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: milestone_one_a
    description: "To calculate the average of particular schema"

  - name: milestone_one_b_max
    description: "To calculate the maximum_value in a given schema"

  - name: milestone_one_b_min
    description: "To calculate the minimum_value in a given schema"
